#!/usr/bin/env node
/*
 * World Cup 2026 Sweeps — public roster builder.
 *
 * Emits public/data/roster.json: a SAFE subset of the entrant list for the
 * pre-season sign-up tracker. It contains ONLY each person's name + paid flag —
 * never tokens, teams, or picks (those live in config/allocations.json,
 * config/picks.json and the private Sheet, not here).
 *
 * Source of truth is config/entrants.json (admin-maintained). Run by the Action
 * on every data refresh, so the public roster tracks paid status automatically.
 * Requires Node 18+.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENTRANTS_FILE = path.join(ROOT, 'config', 'entrants.json');
const ROSTER_FILE = path.join(ROOT, 'public', 'data', 'roster.json');

function readJSON(file, fallback) {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; }
}

function writeIfChanged(file, text) {
  let prev = null;
  try { prev = fs.readFileSync(file, 'utf8'); } catch { /* new file */ }
  if (prev === text) return false;
  fs.writeFileSync(file, text);
  return true;
}

function main() {
  const entrants = readJSON(ENTRANTS_FILE, { people: [] });
  const people = Array.isArray(entrants.people) ? entrants.people : [];

  // Strip to name + paid only — this file is public.
  const roster = {
    _comment: 'Generated by scripts/build-roster.js from config/entrants.json. SAFE public subset: name + paid only, no tokens/teams/picks. Do not edit by hand.',
    generatedAt: new Date().toISOString(),
    entrants: people
      .filter((p) => p && p.name)
      .map((p) => ({ name: p.name, paid: p.paid === true }))
  };

  const changed = writeIfChanged(ROSTER_FILE, JSON.stringify(roster, null, 2) + '\n');
  const paid = roster.entrants.filter((p) => p.paid).length;
  console.log(`[roster] ${paid}/${roster.entrants.length} paid. roster.json ${changed ? 'updated' : 'unchanged'}.`);
}

main();
