#!/usr/bin/env node
/*
 * World Cup 2026 Sweeps — sheet -> static JSON sync.
 *
 * After the self-serve draw/picks flow, the private Google Sheet (via its Apps
 * Script `export` endpoint) is the source of truth. This pulls that token-free
 * snapshot and writes the two static files the leaderboard already reads:
 *
 *   config/allocations.json   every entrant's two sealed teams
 *   config/picks.json         the two player picks of everyone who has submitted
 *
 * The export endpoint never returns tokens, so nothing secret is ever written
 * into the (public) repo. The web-app URL lives in config/backend.json.
 *
 * No-op (exit 0) when backend.json has no apiUrl yet, so the data job keeps
 * working before the backend is wired up. Requires Node 18+.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const BACKEND_FILE = path.join(ROOT, 'config', 'backend.json');
const POTS_FILE = path.join(ROOT, 'config', 'pots.json');
const PLAYERS_FILE = path.join(ROOT, 'public', 'data', 'players.json');
const ALLOCATIONS_FILE = path.join(ROOT, 'config', 'allocations.json');
const PICKS_FILE = path.join(ROOT, 'config', 'picks.json');

function readJSON(file, fallback) {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; }
}

// Write only when content actually changed, so the Action commits nothing on
// no-op runs.
function writeIfChanged(file, text) {
  let prev = null;
  try { prev = fs.readFileSync(file, 'utf8'); } catch { /* new file */ }
  if (prev === text) return false;
  fs.writeFileSync(file, text);
  return true;
}

async function main() {
  const backend = readJSON(BACKEND_FILE, {});
  const apiUrl = (backend.apiUrl || '').trim();
  if (!apiUrl) {
    console.log('[sync] config/backend.json has no apiUrl yet; skipping.');
    return;
  }

  let doc;
  try {
    const res = await fetch(`${apiUrl}?action=export`, { headers: { 'User-Agent': 'wc-2026-sweeps sync' } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    doc = await res.json();
  } catch (e) {
    console.warn(`[sync] export fetch failed: ${e.message}; leaving static JSON untouched.`);
    return;
  }
  if (!doc || doc.ok === false || !Array.isArray(doc.people)) {
    console.warn('[sync] export returned no usable rows; leaving static JSON untouched.');
    return;
  }

  // Name hints (optional; live data overrides them on the board).
  const pots = readJSON(POTS_FILE, {});
  const teamName = new Map();
  for (const t of [...(pots.potA || []), ...(pots.potB || [])]) {
    if (t && t.id != null) teamName.set(String(t.id), t.name || null);
  }
  const playersDoc = readJSON(PLAYERS_FILE, { players: [] });
  const playerInfo = new Map();
  for (const p of playersDoc.players || []) playerInfo.set(String(p.id), p);

  const allocations = {
    _comment: 'Generated by scripts/sync-sheet.js from the private Sheet export. Do not edit by hand.',
    people: doc.people
      .filter((p) => p && p.name && p.teamA_id && p.teamB_id)
      .map((p) => ({
        name: p.name,
        teams: [
          { id: String(p.teamA_id), name: teamName.get(String(p.teamA_id)) || null },
          { id: String(p.teamB_id), name: teamName.get(String(p.teamB_id)) || null }
        ]
      }))
  };

  const picks = {
    _comment: 'Generated by scripts/sync-sheet.js from the private Sheet export (submitted picks only). Do not edit by hand.',
    people: doc.people
      .filter((p) => p && p.name && p.submitted && p.pickFwd_id && p.pickOther_id)
      .map((p) => {
        const fwd = playerInfo.get(String(p.pickFwd_id));
        const other = playerInfo.get(String(p.pickOther_id));
        return {
          name: p.name,
          players: [
            { id: String(p.pickFwd_id), name: (fwd && fwd.name) || null, position: 'F' },
            { id: String(p.pickOther_id), name: (other && other.name) || null, position: 'M' }
          ]
        };
      })
  };

  const aChanged = writeIfChanged(ALLOCATIONS_FILE, JSON.stringify(allocations, null, 2) + '\n');
  const pChanged = writeIfChanged(PICKS_FILE, JSON.stringify(picks, null, 2) + '\n');
  console.log(
    `[sync] ${allocations.people.length} allocations, ${picks.people.length} submitted picks. ` +
    `allocations.json ${aChanged ? 'updated' : 'unchanged'}, picks.json ${pChanged ? 'updated' : 'unchanged'}.`
  );
}

main().catch((e) => { console.error(`[sync] FATAL: ${e.stack || e.message}`); process.exit(1); });
